services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb_order_service
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: order-service
    volumes:
      - ./data:/data/db